version: "3.7"
services:
  caddy:
    image: ghcr.io/bytemain/caddyx:main
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
      - CADDY_DOCKER_CADDYFILE_PATH=/etc/caddy/Caddyfile
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
      - ./config:/etc/caddy
    restart: unless-stopped

networks:
  caddy:
    external: true

volumes:
  caddy_data: {}
